### ISSUE TITLE
Link time optimatization

### ISSUE THREAD

**Issue by nicmcd** [ssnetsim/supersim#20]
Previously, when SuperSim used basic makefiles, link time optimization (LTO) was shown to provide significant execution speedup. The -flto flag was used. See here: https://github.com/ssnetsim/supersim/blob/12110bdeadc77eec91f6bdc49508c3cd4c5703ff/Makefile#L48

After converting to Bazel, LTO has been unsuccessful to build. Fix it.

**Comment by nicmcd** [comment]
Use "--features=thinlto"

**Comment by knrafto** [comment]
why not put it in the BUILD file so it's used by default?

**Comment by nicmcd** [comment]
That would be a .bazelrc file and yes that could be added.

**Comment by knrafto** [comment]
oh. It can't be set via the `features` attribute of a BUILD rule?

**Comment by nicmcd** [comment]
It probably could, but why? I don't think we'd want to mandate a feature. You don't want to use LTO if you are just trying to get something to quick compile.
